#!/usr/bin/env bash

#
#  sysinfo - Display a summary of system hardware, operating system, and networking
#
#  Author:   Jed Record <erecord@lenovo.com> (jed.record@gmail.com)
#
#  Copyright (C) 2018, 2019, 2020 Jed Record, Lenovo, and contributors
#
#  Version:     1.0.3
#
#  Last update: 9 March 2020

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; Version 2 (GPLv2)

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License along
#  with this program; if not, write to the Free Software Foundation, Inc.,
#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Full license text at: https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt

# TODO: Substitute sed for complex gawk statements (ie: match, gsub)
# TODO: Produce alternative output for commands some systems do not support
#            eg: ip, ss, dmidecode, lscpu, df, du, xargs, tput, free

NAME="Sysinfo"
PURPOSE="Display a summary of system hardware, operating system, and networking"
VERSION="1.0.3"
UPDATED="9 March 2020"
AUTHOR="Jed Record"
EMAIL="erecord@lenovo.com"
WEB="https://github.com/jedrecord/sysinfo"
COPYRIGHT="Copyright (C) 2018, 2019, 2020 Jed Record, Lenovo and contributors
License: GNU General Public License, version 2
         <https://gnu.org/licenses/gpl-2.0.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law."
USAGE="Usage: sysinfo [OPTIONS]

Option          Meaning
 -a             Show detailed system information
 -d             Show disk usage
 -h, --help     Show usage and options
 -l             Print a longer list of info than default
 --license      Print full program license to the screen
 -p             Show active services listening on TCP + UDP ports
 -s             Show a short summary
 -v, --version  Print version info
 -w             List configured web directories"

#--------------------------------------
#             Main
#--------------------------------------
main()
{
  while getopts ":-: :a :d :l :p :r: :s :v :w" opt; do
    case "$opt" in
        -) check_long_opts "${OPTARG}"; shift ;;
        a) opt_all=true ;;
        d) opt_disk=true ;;
        l) opt_long=true ;;
        p) opt_ports=true ;;
        r) RHOST="${OPTARG}"; exec_remote ;;
        s) opt_short=true ;;
        v) show_version ;;
        w) opt_web=true ;;
       \?) show_help ;;
        :) echo "Opt ${OPTARG} requires an argumemt" 1>2& ;;
    esac
  done
  if [ $? -ne 0 ];then opt_none=true; fi
  shift $((OPTIND -1))

  begin
  if [ "$opt_short" = true ];then
    system
    show_os
    cpu
    mem
    exit 0;
  fi
  header
  name
#  ipaddr
  ethip4
  if [ "$opt_ports" = true ];then
#    iface
    tsvc
    usvc
    exit 0
  fi
  system
  show_os
  cpuinfo
  if [ "$opt_web" = true ];then web; exit 0; fi
  if [ "$opt_disk" = true ];then
    space
    dirs
    exit 0
  fi
  gpu
  mem
#  iface
  if [ "$opt_all" = true ] || [ "$opt_long" = true ];then
    tsvc
    usvc
  else
    tsvc
  fi
  # Stop here with no args (default)
  if [ "$opt_none" ];then
    exit 0
  fi
  if [ "$opt_long" = true ];then
    #dirs
    #askweb
    log
  elif [ "$opt_all" = true ];then
    space
    dirs
    web
    log
  fi
  exit 0 #-------- End --------
}

#--------------------------------------
#           Functions
#--------------------------------------
begin(){
  # If run from a terminal use colors
  if [[ -t 1 && $(command -v tput) ]];then
    bold_text=$(tput bold)
    red_text=$(tput setaf 1)
    green_text=$(tput setaf 2)
    yellow_text=$(tput setaf 3)
    cyan_text=$(tput setaf 6)
    normal_text=$(tput sgr0)
  else
    bold_text=
    red_text=
    green_text=
    yellow_text=
    cyan_text=
    normal_text=
  fi
}
check_long_opts(){
  local long_option="$1"
  case ${long_option} in
    about) show_about ;;
    license) show_license ;;
    version) show_version ;;
    "help") show_help ;;
    *) echo "\"--${long_option}\" is an invalid option"; show_help ;;
  esac
}
show_about(){
	echo "${NAME} version ${VERSION} (updated ${UPDATED})"
	echo "${PURPOSE}"
	echo "${USAGE}"
  echo
	echo "${COPYRIGHT}"
  echo
	echo "Contact: ${AUTHOR} <${EMAIL}>"
  echo "Website: ${WEB}"
	exit 0
}
show_version(){
	echo "${NAME} version ${VERSION} (updated ${UPDATED})"
	echo "${COPYRIGHT}"
  echo
	echo "Contact: ${AUTHOR} <${EMAIL}>"
  echo "Website: ${WEB}"
	exit 0
}
show_help(){
	echo "${NAME} version ${VERSION} (updated ${UPDATED})"
	echo "${USAGE}"
	exit 0
}
show_license(){
	echo "${NAME} version ${VERSION} (updated ${UPDATED})"
	echo "${COPYRIGHT}"
  echo
  echo "${LICENSE}"
  echo
	echo "Contact: ${AUTHOR} <${EMAIL}>"
  echo "Website: ${WEB}"
	exit 0
}
exec_remote(){
  local sysinfo="$(cd "$(dirname "$0")" ; pwd -P )/$(basename "$0")"
  ssh "${RHOST}" "bash -s" < ${sysinfo}
  exit $?
}
header(){
  echo "-----------------------------------------------------"
}
name(){
  printf "Name: ${bold_text}%s${normal_text}\n" $(hostname)
}
ipaddr(){
  local ips=""
  for ipa in $(ip a|awk '/global/ {print $2}'|sed 's/\/.*//');do
    ips="${ipa}, ${ips}"
  done
  printf "IP addresses: ${ips%,*}\n"
}
ethip4(){
  local eips=""
  local interfaces=""
  if command -v gawk > /dev/null 2>&1;then
    interfaces="$(ip -4 -o a show scope global up | awk 'match($4,/([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})/,ip) {print $2":"ip[1]}')"
  else
    interfaces="$(ip -4 -o a show scope global up | awk '{print $2":"$4}'|sed "s/\/.*//")"
  fi
  local i=0
  for eip in ${interfaces};do
    if [[ $i -eq 0 ]]; then
      eips="${eip}"
      i=1
    else
      eips="${eips}, ${eip}"
    fi
  done
  printf "IP4 addresses: ${eips}\n"
}
system(){
  if [[ $EUID -eq 0 ]] && command -v dmidecode > /dev/null 2>&1;then
    mfg="$(dmidecode -s system-manufacturer)"
    prod="$(dmidecode -s system-product-name)"
  else
    mfg="$(cat /sys/devices/virtual/dmi/id/sys_vendor)"
    prod="$(cat /sys/devices/virtual/dmi/id/product_name)"
  fi
  arch="$(arch)"
  # Sometimes we see newlines in dmi output, supress with echo -n
  echo -n "System: "
  if [[ -f /.dockerenv ]]
  then
    echo -n "Docker container on "
  fi
  echo -n "${mfg} ${prod} (${arch})"
  echo
}
show_os(){
  if [[ -f /etc/lsb-release ]];then
    source /etc/lsb-release
    os_string="${red_text}${DISTRIB_ID}${normal_text} ${DISTRIB_RELEASE}"
		if [[ -n "${DISTRIB_CODENAME}" ]];then
			os_string="${os_string} (${DISTRIB_CODENAME})"
		fi
  elif [[ -f /etc/os-release ]];then
    source /etc/os-release
    os_string="${red_text}${NAME}${normal_text} ${VERSION_ID}"
		if [[ -n "${VERSION_CODENAME}" ]];then
			os_string="${os_string} (${VERSION_CODENAME})"
		fi
  else
    os_string="${red_text}$(uname)${normal_text} Kernel: $(uname -r)"
  fi
  echo "OS: ${os_string} Kernel: $(uname -r)"
}
cpu(){
  if command -v gawk > /dev/null 2>&1;then
    cpucount="$(lscpu|awk -F: '/^CPU\(s\):/ {match($2,/([0-9]+)/,n);print n[1]}')"
    cpumodel="$(lscpu|awk -F: '/^Model name:/ {match($2,/\s+(\w.*)/,n);print n[1]}')"
  else
    cpucount="$(lscpu|awk -F: '/^CPU\(s\):/ {print $2}'|sed "s/ //g")"
    cpumodel="$(lscpu|awk -F: '/^Model name:/ {print $2}'|sed "s/^\s+//g")"
  fi
  printf "CPU Info: ${bold_text}%s${normal_text} x " $cpucount
  echo $cpumodel
}
cpuinfo(){
  cpu
  local skts=""
  local cps=""
  local tpc=""
  local cpucache=""
  if command -v gawk > /dev/null 2>&1;then
    skts="$(lscpu|awk -F: '/^Socket\(s\):/ {match($2,/([0-9]+)/,n);print n[1]}')"
    cps="$(lscpu|awk -F: '/^Core\(s\) per socket:/ {match($2,/([0-9]+)/,n);print n[1]}')"
    tpc="$(lscpu|awk -F: '/^Thread\(s\) per core:/ {match($2,/([0-9]+)/,n);print n[1]}')"
  else
    skts="$(lscpu|awk -F: '/^Socket\(s\):/ {print $2}'|sed "s/ //g")"
    cps="$(lscpu|awk -F: '/^Core\(s\) per socket:/ {print $2}'|sed "s/ //g")"
    tpc="$(lscpu|awk -F: '/^Thread\(s\) per core:/ {print $2}'|sed "s/ //g")"
  fi
  printf "%s sockets | %s cores per socket | %s threads per core | " \
    "${skts}" "${cps}" "${tpc}"
  if command -v numfmt > /dev/null 2>&1;then
    # If numfmt > 8.22
    #cpucache="$(cat /proc/cpuinfo|awk -F": " '/^cache size/ {print $2}'|numfmt -d _ --from=iec --to=iec --suffix=B --format="%.1f")"
    cpucache="$(cat /proc/cpuinfo|awk -F": " '/^cache size/ {print $2;exit;}'|numfmt -d _ --from=iec --to=iec --suffix=B)"
  else
    cpucache="$(cat /proc/cpuinfo|awk -F": " '/^cache size/ {print $2;exit;}')"
  fi
  echo "${cpucache} cache"
}
gpu(){
  if command -v nvidia-smi > /dev/null 2>&1;then
    #gpus="$(nvidia-smi --query-gpu=gpu_name 2> /dev/null)"
    #echo "GPU Info: ${bold_text}%s${normal_text}\n" "$gpus"
    echo "GPU(s):"
    nvidia-smi --query-gpu=gpu_name --format=csv,noheader 2> /dev/null
  fi
}
mem(){
  avail="$(free -h | awk '/Mem:/{print $2}')"
  freem="$(free -h | awk '/Mem:/{print $4}')"
  if [[ "$freem" =~ "M" ]];then
    freem="${red_text}$freem${normal_text}"
  fi
  printf "Total memory: %s Free memory: %s\n" "$avail" "$freem"
}
iface(){
  printf "Network interfaces: "
  for foo in $(ip link show up|grep -i "state up"|awk -F": " '{print $2}'); do
    printf "$foo "
  done
  echo
}
tsvc(){
  local ports=""
  printf "TCP ports listening: "
  if [[ $EUID -ne 0 ]];then
    if command -v gawk > /dev/null 2>&1;then
      ports="$(ss -ltn | awk 'NR>1 match($4,/.*:([0-9]+)$/,m){print m[1]}'|sort -u)"
    else
      ports="$(ss -ltn | awk 'NR>1 {print $4}'|sed -E "s/.*:([0-9]+)$/\\1/"|sort -u)"
    fi
    for tsrv in ${ports};do
      local tn="$(grep "\s${tsrv}/tcp" /etc/services|awk '{print $1}')"
      if [[ -z "${tn}" ]];then
        printf "%s " "${tsrv}"
      else
        printf "%s(%s) " "${tsrv}" "${tn}"
      fi
      done
    echo
  else
    if command -v gawk > /dev/null 2>&1;then
      ports="$(ss -pltn | awk 'NR>1 {{match($4,/.*:([0-9]+)$/,port) match($6,/users:\(\(\"([a-z][-a-z0-9_.]+)\"/,name)} {print name[1]"("port[1]")"}};' | sort -u)"
    else
      ports="$(ss -pltn | awk 'NR>1 {print $4,$6}' |sed -E "s/.*:([0-9]+) users:\(\(\"([^\"]+).*/\\1(\\2)/"|sort -u)"
    fi
    for tsrv in ${ports};do
      printf "$tsrv "
    done
    echo
  fi
}
usvc(){
  local ports=""
  printf "UDP ports listening: "
  if [[ $EUID -ne 0 ]];then
    if command -v gawk > /dev/null 2>&1;then
      ports="$(ss -lun | awk 'NR>1 match($4,/.*:([0-9]+)/,m){print m[1]}'|sort -u)"
    else
      ports="$(ss -lun | awk 'NR>1 {print $4}'|sed -E "s/.*:([0-9]+)$/\\1/"|sort -u)"
    fi
    for usrv in ${ports};do
      local un="$(grep "\s${usrv}/udp" /etc/services|awk '{print $1}')"
      if [[ -z "${un}" ]];then
        printf "%s " "${usrv}"
      else
        printf "%s(%s) " "${usrv}" "${un}"
      fi
    done
    echo
  else
    if command -v gawk > /dev/null 2>&1;then
      ports="$(ss -plun | awk 'NR>1 {{match($4,/.*:([0-9]+)$/,port) match($6,/users:\(\(\"([a-z][-a-z0-9_.]+)\"/,name)} {print name[1]"("port[1]")"}};' | sort -u)"
    else
      ports="$(ss -plun | awk 'NR>1 {print $4,$6}' |sed -E "s/.*:([0-9]+) users:\(\(\"([^\"]+).*/\\1(\\2)/"|sort -u)"
    fi
    for usrv in ${ports};do
      printf "$usrv "
    done
    echo
  fi
}
body() {
    IFS= read -r header
    printf '%s\n' "$header"
    "$@"
}
space(){
  echo "Disk space: "
  #df -h --output=target,size,avail,pcent -t xfs -t ext3 -t ext4
  df -h --output=target,fstype,size,avail,pcent \
    | body sort -rhk 5 \
    | grep -v 'tmpfs'
}
dirs(){
  echo
  printf "Gathering filesystem info, this may take a minute..."
  local homes="$(du -sh /home/* 2>/dev/null | sort -rh | head -5)"
  local vars="$(du -sh /var/* 2>/dev/null | sort -rh | egrep '^[0-9][0-9][0-9]+M|^[0-9.]+G' | head -5)"
  if command -v tput > /dev/null 2>&1; then
    # Clear to beginning of line
    printf $(tput el1)
    # Move cursor left 52 spaces (Back to beginning of line)
    printf $(tput cub 52)
    # Move cursor up 1 line
    printf $(tput cuu1)
  else
    # Mover cusor back 52 spaces (to beginning of line)
    echo -en "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
    # Overight previous text
    echo -n "                                                    "
    # Move cursor back to beginning of line
    echo -en "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b"
  fi
  if [[ ! -z ${homes+x} ]]; then
    echo "Top home directories by size: "
    echo "${homes}"
  fi
  if [[ ! -z ${vars+x} ]]; then
    echo "Large var directories: "
    echo "${vars}"
  fi
}
web(){
  find /etc/apache2 -name "*.conf" 2>/dev/null \
    | xargs egrep -i '^ServerName\s+\w|^ServerRoot\s+\w|^<Directory ' \
    | awk -F ":" 'gsub(/\s+/," ",$2){print "apache2:"$2}' \
    | sed "s/apache2: /apache2:/" \
    | sed -r "s/<Directory \"?([^>\"]+).*/Dir:\1/" \
    | sort -r -u
  find /etc/httpd -name "*.conf" 2>/dev/null \
    | xargs egrep -i '^ServerName\s+\w|^DocumentRoot\s+\w|^<Directory ' \
    | awk -F ":" 'gsub(/\s+/," ",$2){print "httpd:"$2}' \
    | sed "s/httpd: /httpd:/" \
    | sed -r "s/<Directory \"?([^>\"]+).*/Dir:\1/" \
    | sort -r -u
  find /etc/nginx /etc/nginx -name "*.conf" 2>/dev/null \
    | xargs egrep -i "server_name\s+\w|location\s+\w|root\s+\w|alias\s+\w|mirror\s+\w" \
    | awk -F ":" 'gsub(/\s+/," ",$2) {print "nginx:"$2}' \
    | sed "s/nginx: /nginx:/" \
    | sed -r "/[^ ]+ [^a-zA-Z]+$/d" \
    | sed "/^nginx:#/d" \
    | sort -r -u
}
askweb(){
  if command -v gawk > /dev/null 2>&1;then
    echo "Web shares: "
    webcount=$(web | wc -l)
    web | head -10
    if [ "$webcount" -gt 10 ]; then
      echo "Press q to quit or any other key to view the more than 10 web directories"
      if read -r -n1 -t 5 -s key_in && [ "$key_in" != "q" ];then
        web | awk 'NR>10 {print}'
      fi
    fi
  elif [ "$opt_web" = true ];then
    echo "Skipping web directories (requires gawk)"
  fi
}
# Not sure how usefull this is, but I think it gives an idea of server health
# TODO: Smart checking of which log to check based on system
log(){
  if [[ $EUID -eq 0 ]];then
    local logsize="$(wc -l /var/log/messages|awk '{print $1}')"
    if [[ "${logsize}" -gt 0 ]];then
      local warnings="$(egrep -i "fail|error" /var/log/messages | wc -l)"
      local warnpct="$(awk -v W="${warnings}" -v L="${logsize}" 'BEGIN {print ((W * 100) / L)}')"
      printf '%s warnings in %s log entries: %.1f%% log error rate\n' "${warnings}" "${logsize}" "${warnpct}"
    fi
  fi
}
read -r -d '' LICENSE <<'EOF'
.                   GNU GENERAL PUBLIC LICENSE
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. This License applies to any program or other work which contains
a notice placed by the copyright holder saying it may be distributed
under the terms of this General Public License.  The "Program", below,
refers to any such program or work, and a "work based on the Program"
means either the Program or any derivative work under copyright law:
that is to say, a work containing the Program or a portion of it,
either verbatim or with modifications and/or translated into another
language.  (Hereinafter, translation is included without limitation in
the term "modification".)  Each licensee is addressed as "you".

Activities other than copying, distribution and modification are not
covered by this License; they are outside its scope.  The act of
running the Program is not restricted, and the output from the Program
is covered only if its contents constitute a work based on the
Program (independent of having been made by running the Program).
Whether that is true depends on what the Program does.

  1. You may copy and distribute verbatim copies of the Program's
source code as you receive it, in any medium, provided that you
conspicuously and appropriately publish on each copy an appropriate
copyright notice and disclaimer of warranty; keep intact all the
notices that refer to this License and to the absence of any warranty;
and give any other recipients of the Program a copy of this License
along with the Program.

You may charge a fee for the physical act of transferring a copy, and
you may at your option offer warranty protection in exchange for a fee.

  2. You may modify your copy or copies of the Program or any portion
of it, thus forming a work based on the Program, and copy and
distribute such modifications or work under the terms of Section 1
above, provided that you also meet all of these conditions:

    a) You must cause the modified files to carry prominent notices
    stating that you changed the files and the date of any change.

    b) You must cause any work that you distribute or publish, that in
    whole or in part contains or is derived from the Program or any
    part thereof, to be licensed as a whole at no charge to all third
    parties under the terms of this License.

    c) If the modified program normally reads commands interactively
    when run, you must cause it, when started running for such
    interactive use in the most ordinary way, to print or display an
    announcement including an appropriate copyright notice and a
    notice that there is no warranty (or else, saying that you provide
    a warranty) and that users may redistribute the program under
    these conditions, and telling the user how to view a copy of this
    License.  (Exception: if the Program itself is interactive but
    does not normally print such an announcement, your work based on
    the Program is not required to print an announcement.)

These requirements apply to the modified work as a whole.  If
identifiable sections of that work are not derived from the Program,
and can be reasonably considered independent and separate works in
themselves, then this License, and its terms, do not apply to those
sections when you distribute them as separate works.  But when you
distribute the same sections as part of a whole which is a work based
on the Program, the distribution of the whole must be on the terms of
this License, whose permissions for other licensees extend to the
entire whole, and thus to each and every part regardless of who wrote it.

Thus, it is not the intent of this section to claim rights or contest
your rights to work written entirely by you; rather, the intent is to
exercise the right to control the distribution of derivative or
collective works based on the Program.

In addition, mere aggregation of another work not based on the Program
with the Program (or with a work based on the Program) on a volume of
a storage or distribution medium does not bring the other work under
the scope of this License.

  3. You may copy and distribute the Program (or a work based on it,
under Section 2) in object code or executable form under the terms of
Sections 1 and 2 above provided that you also do one of the following:

    a) Accompany it with the complete corresponding machine-readable
    source code, which must be distributed under the terms of Sections
    1 and 2 above on a medium customarily used for software interchange; or,

    b) Accompany it with a written offer, valid for at least three
    years, to give any third party, for a charge no more than your
    cost of physically performing source distribution, a complete
    machine-readable copy of the corresponding source code, to be
    distributed under the terms of Sections 1 and 2 above on a medium
    customarily used for software interchange; or,

    c) Accompany it with the information you received as to the offer
    to distribute corresponding source code.  (This alternative is
    allowed only for noncommercial distribution and only if you
    received the program in object code or executable form with such
    an offer, in accord with Subsection b above.)

The source code for a work means the preferred form of the work for
making modifications to it.  For an executable work, complete source
code means all the source code for all modules it contains, plus any
associated interface definition files, plus the scripts used to
control compilation and installation of the executable.  However, as a
special exception, the source code distributed need not include
anything that is normally distributed (in either source or binary
form) with the major components (compiler, kernel, and so on) of the
operating system on which the executable runs, unless that component
itself accompanies the executable.

If distribution of executable or object code is made by offering
access to copy from a designated place, then offering equivalent
access to copy the source code from the same place counts as
distribution of the source code, even though third parties are not
compelled to copy the source along with the object code.

  4. You may not copy, modify, sublicense, or distribute the Program
except as expressly provided under this License.  Any attempt
otherwise to copy, modify, sublicense or distribute the Program is
void, and will automatically terminate your rights under this License.
However, parties who have received copies, or rights, from you under
this License will not have their licenses terminated so long as such
parties remain in full compliance.

  5. You are not required to accept this License, since you have not
signed it.  However, nothing else grants you permission to modify or
distribute the Program or its derivative works.  These actions are
prohibited by law if you do not accept this License.  Therefore, by
modifying or distributing the Program (or any work based on the
Program), you indicate your acceptance of this License to do so, and
all its terms and conditions for copying, distributing or modifying
the Program or works based on it.

  6. Each time you redistribute the Program (or any work based on the
Program), the recipient automatically receives a license from the
original licensor to copy, distribute or modify the Program subject to
these terms and conditions.  You may not impose any further
restrictions on the recipients' exercise of the rights granted herein.
You are not responsible for enforcing compliance by third parties to
this License.

  7. If, as a consequence of a court judgment or allegation of patent
infringement or for any other reason (not limited to patent issues),
conditions are imposed on you (whether by court order, agreement or
otherwise) that contradict the conditions of this License, they do not
excuse you from the conditions of this License.  If you cannot
distribute so as to satisfy simultaneously your obligations under this
License and any other pertinent obligations, then as a consequence you
may not distribute the Program at all.  For example, if a patent
license would not permit royalty-free redistribution of the Program by
all those who receive copies directly or indirectly through you, then
the only way you could satisfy both it and this License would be to
refrain entirely from distribution of the Program.

If any portion of this section is held invalid or unenforceable under
any particular circumstance, the balance of the section is intended to
apply and the section as a whole is intended to apply in other
circumstances.

It is not the purpose of this section to induce you to infringe any
patents or other property right claims or to contest validity of any
such claims; this section has the sole purpose of protecting the
integrity of the free software distribution system, which is
implemented by public license practices.  Many people have made
generous contributions to the wide range of software distributed
through that system in reliance on consistent application of that
system; it is up to the author/donor to decide if he or she is willing
to distribute software through any other system and a licensee cannot
impose that choice.

This section is intended to make thoroughly clear what is believed to
be a consequence of the rest of this License.

  8. If the distribution and/or use of the Program is restricted in
certain countries either by patents or by copyrighted interfaces, the
original copyright holder who places the Program under this License
may add an explicit geographical distribution limitation excluding
those countries, so that distribution is permitted only in or among
countries not thus excluded.  In such case, this License incorporates
the limitation as if written in the body of this License.

  9. The Free Software Foundation may publish revised and/or new versions
of the General Public License from time to time.  Such new versions will
be similar in spirit to the present version, but may differ in detail to
address new problems or concerns.

Each version is given a distinguishing version number.  If the Program
specifies a version number of this License which applies to it and "any
later version", you have the option of following the terms and conditions
either of that version or of any later version published by the Free
Software Foundation.  If the Program does not specify a version number of
this License, you may choose any version ever published by the Free Software
Foundation.

  10. If you wish to incorporate parts of the Program into other free
programs whose distribution conditions are different, write to the author
to ask for permission.  For software which is copyrighted by the Free
Software Foundation, write to the Free Software Foundation; we sometimes
make exceptions for this.  Our decision will be guided by the two goals
of preserving the free status of all derivatives of our free software and
of promoting the sharing and reuse of software generally.

                            NO WARRANTY

  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN
OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS
TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU.  SHOULD THE
PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,
REPAIR OR CORRECTION.

  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,
INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING
OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED
TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY
YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER
PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

                     END OF TERMS AND CONDITIONS
EOF
#--------------------------------------
#           end functions
#--------------------------------------
main "$@"
